### ISSUE TITLE
Context Menu Incorrect

### ISSUE THREAD

**Issue by jfdawes** [MOARdV/AviationLights#12]
Using KSP 64 bit version 1.4.5.2243 the context menu for an Aviation Light just shows the model selector, regardless of whether advanced tweakables are enabled or not.

![aviationlightmenu](https://user-images.githubusercontent.com/4492621/46049398-f9269f80-c0e2-11e8-832d-0eafca875b46.png)

**Comment by MOARdV** [comment]
I need to see logs.  The only reason the light would be missing tweakables is an incorrect or incomplete installation of the mod.

**Comment by jfdawes** [comment]
This installation is OOTB.  The repo was downloaded as-is and AviationLights-master\GameData\AviationLights folder was copied from the repo to the KSP installation.

Please let me know what logs you would like to see and if you would like more than default logs how to configure those.

**Comment by MOARdV** [comment]
The repo does not contain the DLL required for the mod to function.  Please download the latest release from the releases tab: https://github.com/MOARdV/AviationLights/releases

**Comment by jfdawes** [comment]
That was it, thanks.  Thanks also for doing this mod, especially solving the issue with the lights attaching below the surface a lot of the time that existed in the old version.
