### ISSUE TITLE
cannot use with kos.  some lights stopped working

### ISSUE THREAD

**Issue by taksuda** [MOARdV/AviationLights#19]
![Capture](https://user-images.githubusercontent.com/29102678/63220037-6db47200-c1be-11e9-8adf-455911bb8e25.PNG)

https://youtu.be/trVyAYGDZzg

**Comment by MOARdV** [comment]
I would suggest bringing this up with the kOS people first.  I don't use kOS, and this mod does not know anything about it.  If the lights stop working after kOS queries the parts, then it sounds like kOS is doing something to cause Aviation Lights to stop working.

**Comment by taksuda** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29102678/63236730-09f17e00-c27e-11e9-9bc1-29d87d2f1b4a.gif)

works with surface mounted lights but your lights looks way way way way more AWESOME.   wish I could use them. damn.   don't worry I will look in to it and see if its something on my end.

**Comment by taksuda** [comment]
ok after messing about in it for a while I have a request. 
https://youtu.be/QzQ5DLp4loI

also can you add at least one light that will work with the press of the U key. (all lights on command)
I am sorry for all the trouble. really am!
also KOS devs have and are trying to make it works as well. (because we all love your lights. ) 
PS: dare you to take a shot every time you hear the word "just"

**Comment by MOARdV** [comment]
Per your video - to select the mode that shows up as the Toggle option in the part action menu, you need to select that mode in the VAB:

![Basic Menu](https://imageshack.com/a/img924/5732/ad9F9z.jpg)

The "Light Mode: Flash" tells you that Toggle Flash will be displayed in flight.  If you press Toggle Light in the VAB, then the light will toggle on and off during flight.

> can you add at least one light that will work with the press of the U key

You can add aviation lights to the Lights action group in the VAB.  The reason I do not make the lights work with the U key by default is there is no way for me to know in advance how they will be used - on, flash, double-flash, or interval.

If I add one of those modes to the Lights action group by default, then a player has to remember to remove it if they are using a different mode, or if they are using a different action group to control aviation lights.

Although, now that I think about it, I think I can improve the interface in the VAB, and maybe change the action group behavior as well.

**Comment by taksuda** [comment]
![2](https://user-images.githubusercontent.com/29102678/63298555-dca2df80-c312-11e9-88cc-52a8d21a343f.gif)
let me first of all say thank you very much. you are a GOD. 
secondly it worked.  I had to change each light but it WORKED. 
and also entire KOS community thanks you. 
thank you for being awesome. 

https://discord.gg/7A5Rhe7 if you ever want to get your hands dirty with the big boys.

**Comment by MOARdV** [comment]
I am happy that the option works, and I am glad that it does not require changes to any mods for you to use Aviation Lights with kOS.  I think the GIF needs to dance music. :)

> https://discord.gg/7A5Rhe7 if you ever want to get your hands dirty with the big boys.

I appreciate the offer, but I have been writing software for almost 30 years.  kOS looks fun, but it is a fun toy next to what I do when I am not playing. :)

**Comment by taksuda** [comment]
dont get discoraged by the way i write code.  I have total of 2 weeks of (any)programming experiance.
 and outch. lol 
oh and gif at 10 fps. need min 60. its supporsed to be police lights. lol
