### ISSUE TITLE
Does this still work with KSP 1.9.x?

### ISSUE THREAD

**Issue by scumola** [MOARdV/AviationLights#21]
Just wondering if this still works with KSP 1.9.x.  I need my blinky lights!

**Comment by MOARdV** [comment]
From a quick check, it looks like it works.  I haven't migrated my dev environment to 1.9.x yet, so my testing has not been thorough.

**Comment by scumola** [comment]
I just made a pull request.  It works with 1.9.2.

**Comment by Promyclon** [comment]
Yes it does. With KSP 1.10 it works too.

**Comment by MOARdV** [comment]
Still works - I never got around to updating the version file.  Sorry about that.
