### ISSUE TITLE
Sudden crash at launch

### ISSUE THREAD

**Issue by Foxlider** [MOARdV/AviationLights#3]
The mod caused Unity to crash suddenly. 
I disabled it and everything worked again. 
[https://pastebin.com/grQTJfUK](https://pastebin.com/grQTJfUK)

**Comment by MOARdV** [comment]
That callstack dump by itself doesn't help me, unfortunately.  Can you please add the KSP logs as well so I have some context to work with?

**Comment by Foxlider** [comment]
[output_log.txt](https://github.com/MOARdV/AviationLights/files/1045459/output_log.txt)

**Comment by MOARdV** [comment]
You are running Aviation Lights v3.13 on KSP 1.2.2.

v3.13 is for KSP 1.3.0, as it states on the release page.  If you're using KSP 1.2.2, you need to use Aviation Lights v3.12.

**Comment by Foxlider** [comment]
I had crashes with ksp 1.3 (but I un installed this game version)

--
Lonchambon Alexis
Etudiant IUT Informatique

**Comment by MOARdV** [comment]
I need the output log for KSP 1.3 and Aviation Lights v3.13 (or, better yet, the current v3,14) to do any effective diagnosis of the problem, since no one else has reported this crash.
