### ISSUE TITLE
Reconfigurable light part decal state not changing in flight

### ISSUE THREAD

**Issue by GHrynk** [MOARdV/AviationLights#6]
It appears the decal for the "on" and "off" state does not change on the new reconfigurable light part while in flight (it works in the VAB).  The only indication of the light's state is the illumination cone hitting nearby objects.

**Comment by MOARdV** [comment]
It looks like this was incompletely implemented for the flight scene.  I spent plenty of time getting it working in the editor, but I didn't extensively test flight.  Oops.
