### ISSUE TITLE
Reconfigurable light part not self illuminating vessel

### ISSUE THREAD

**Issue by GHrynk** [MOARdV/AviationLights#7]
Not sure if this was a deliberate design choice, but the new reconfigurable light part does not self illuminate the vessel as the other parts do.  Suggested changes include adding a tweakable slider control to extend the illumination cone beyond 180 degrees or adding a VAB/SPH toggle that sets it as a pure spherical light source (which the other parts appear to be).

**Comment by MOARdV** [comment]
The toggle is by far easier to implement (Unity lets me switch between point and spot on-the-fly), so I'm going to take that route.
