### ISSUE TITLE
version file doesn't contain right value

### ISSUE THREAD

**Issue by MaximeBrean** [MOARdV/AviationLights#9]
As v4.0.4, the version file doesn't contain the correct version value.
Without the right version, KSP-AVC can't flag the mod as being outdated.

**Comment by MOARdV** [comment]
So I did.

**Comment by MOARdV** [comment]
Updated it on GitHub, and replace the ZIP file with one that contains the updated file.

**Comment by MaximeBrean** [comment]
It works :)

Thanks !
